// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otmrqmddybakvpzcjgol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90bXJxbWRkeWJha3ZwemNqZ29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTE1MDgsImV4cCI6MjA2Mjc4NzUwOH0.iJjucNyWDPwSFmyY4s1YbvlEoB9HD0sV9RgDM97W0sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);